// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package melisqlc

import (
	"time"
)

type User struct {
	ID        int32
	Login     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
