// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package casadocodigosqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID          int32
	Name        string
	Email       string
	Description *string
	CreatedAt   pgtype.Timestamp
}

type Book struct {
	ID             int32
	Title          string
	Abstract       string
	TableOfContent string
	Price          float64
	NumberOfPages  int32
	Isbn           string
	PublishDate    pgtype.Date
	CreatedAt      pgtype.Timestamp
	CategoryID     *int32
	AuthorID       int32
}

type Category struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
}
